###########
# site.title

title:    'Classyfy'
subtitle: 'CS 175: Project in AI (in Minecraft with Project Malmo)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-minimal
